version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: ./Docker/Dockerfile
    volumes:
      - ./home/app:/app
    deploy:
      resources:
        reservations:
          devices:
            - nvidia
            count: 1
            capabilities: [gpu] 
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
      - "${TENSORBOARD_PORT}:${TENSORBOARD_PORT}"
    env_file:
      - ./.env
    entrypoint: jupyter lab --ip=0.0.0.0 --port=${JUPYTER_PORT} --no-browser --allow-root