version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: ./Docker/Dockerfile.gpu
    volumes:
      - ./GPT.ipynb:/app/GPT.ipynb
      - ./Data:/app/Data
      - ./checkpoint:/app/checkpoint
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia 
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}"
      - "${TENSORBOARD_PORT}:${TENSORBOARD_PORT}"
    env_file:
      - ./.env
    entrypoint: jupyter lab --ip=0.0.0.0 --port=${JUPYTER_PORT} --no-browser --allow-root
